
package myDemoApp;

/*
* This Java source file was generated by the Gradle 'init' task.
*/

import java.util.ArrayList;

public class App {
public static int sum(ArrayList<Integer> array,int t,int e){ // arraylist must have positive integers >0
if(array==null || array.size()==0) return 0;
for(int i: array)
if(i<=0) return 0;
return array.get(t)+array.get(e);
}
public static void main(String[] args){
System.out.println("hi");
}
}


