/*
* This Java source file was generated by the Gradle 'init' task.
*/
package myDemoApp;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;

class AppTest {
@Test 
public void controlNegative() {
ArrayList<Integer> array = new ArrayList<>(Arrays.asList(-11,2,3,4));
if(App.sum(array,0,1)==0) assertTrue(true);
}

@Test
public void testTrue(){
ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1,2,3,4));
int e=array.get(0)+array.get(1);
int g=App.sum(array, 0, 1);
if(e==g) assertTrue(true);
}
@Test
public void testFalse(){
ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1,2,3,4));
int t=1;
int c=App.sum(array, 0, 1);
if(t!=c) assertFalse(false);
}
@Test
public void testEmptyArray(){
ArrayList<Integer> array = new ArrayList<>();
int c=0;
int k=App.sum(array, 0, 1);
if(c==k) assertTrue(true);
}
@Test
public void testNull(){
int c=0;
int k=App.sum(null,0,1);
if(c==k) assertTrue(true);
}
public void checkIndicesPositive(){
    int c=0;
    ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1,2,3,4));
    int k=App.sum(array,-1,-3);
    if(c==k) assertTrue(true);
    
}
public void checkAllOfThem(){
    if(App.sum(null,null,null)==0) assertTrue(true);
    
}
public void checkIndicesNull(){
    int c=0;
    ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1,2,3,4));
    int k=App.sum(array,null,null);
    if(c==k) assertTrue(true);
}
public void checkSize(){
    ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1));
    if(App.sum(array,1,2)==0) assertTrue(true);
}
}
